# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: AMS Open Radar Short Course 2023
author: the <a href="https://openradarscience.org/">Open Radar</a> Community
logo: notebooks/images/logos/pythia_logo-white-rtext.svg
email: mgrover@anl.gov
copyright: "2023"

description: A sample cookbook description.
thumbnail: thumbnail.png
tags:
  domains:
    - sampledomain
  packages:
    - samplepackage

execute:
  # To execute notebooks via a binder instead, replace 'cache' with 'binder'
  execute_notebooks: 'auto'
  timeout: 1200
  allow_errors: True # cells with expected failures must set the `raises-exception` cell tag

# Add a few extensions to help with parsing content
parse:
  myst_enable_extensions: # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - replacements
    - smartquotes
    - substitution

sphinx:
  config:

    html_favicon: notebooks/images/icons/favicon.ico
    html_last_updated_fmt: '%-d %B %Y'
    html_theme: sphinx_pythia_theme
    html_permalinks_icon: '<i class="fas fa-link"></i>'
    html_theme_options:
      home_page_in_toc: true
      repository_url: https://github.com/openradar/ams-open-radar-2022/ # Online location of your book
      repository_branch: main # Which branch of the repository should be used when creating links (optional)
      use_issues_button: true
      use_repository_button: true
      use_edit_page_button: true
      github_url: https://github.com/openradar
      icon_links:
        - name: YouTube
          url: https://www.youtube.com/channel/UCoZPBqJal5uKpO8ZiwzavCw
          icon: fab fa-youtube-square
          type: fontawesome
      launch_buttons:
        binderhub_url: http://binder.projectpythia.org
        notebook_interface: jupyterlab
      extra_navbar: |
        Theme by <a href="https://projectpythia.org">Project Pythia</a>.<br><br>
        All code in Pythia Cookbooks is licensed under Apache 2.0. All other non-code content is licensed under <a href="https://creativecommons.org/licenses/by/4.0/">Creative Commons BY 4.0 (CC BY 4.0)</a>.<br><br>
      logo_link: https://openradarscience.org
      navbar_links:
        - name: Home
          url: https://openradarscience.org
        - name: Radar Cookbook
          url: https://projectpythia.org/radar-cookbook
      footer_logos:
        NCAR: notebooks/images/logos/NCAR-contemp-logo-blue.svg
        Unidata: notebooks/images/logos/Unidata_logo_horizontal_1200x300.svg
        UAlbany: notebooks/images/logos/UAlbany-A2-logo-purple-gold.svg
