name: ams-open-radar-2023-dev
channels:
  - conda-forge
  - pyviz
dependencies:
  - python>=3.10
  - jupyter-book
  - jupyterlab
  - jupyter_server
  - arm_pyart
  - matplotlib
  - pydda
  - tensorflow
  - wradlib
  - xradar
  - cartopy
  - metpy
  - pydda
  - s3fs
  - geoviews
  - tensorflow-probability
  - certifi>=2023.07.22
  - cryptography>=41.0.3
  - semver>=3.0.1
  - pip
  - pip:
      - sphinx-pythia-theme
      - tornado>=6.3.3
