name: ams-open-radar-2023-dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyter-book
  - numpy
  - scipy
  - matplotlib
  - cartopy
  - pandas
  - xarray
  - arm_pyart
  - xradar
  - wradlib
  - dask
  - tqdm
  - hvplot
  - rioxarray
  - geopandas
  - datashader
  - pyrad_arm
  - cookiecutter
  # this is needed for baltrad compilation
  - compilers
  - make
  - gnuconfig
  - bash
  - s3fs
  - libaec
  - coreutils
  - autoconf
  - automake
  - tar
  - libblas=*=*netlib
  - liblapacke=*=*netlib
  # this is needed for notebooks
  - pip
  - pyviz_comms>=2.0
  - nbstripout
  - metpy
  - pydda
  - tobac
  - tensorflow
  - zip
  - certifi>=2023.07.22
  - cryptography>=41.0.3
  - semver>=3.0.1
  - nbgitpuller
  - pip
  - pip:
      - sphinx-pythia-theme
      - tornado>=6.3.3