name: trigger-book-build
on:
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/build-book-pullrequest.yaml
    with:
      environment_name: ams-open-radar-2023-dev
      environment_file: environment.yml
      path_to_notebooks: ./
      use_cached_environment: 'false'  # This is default, not strickly needed. Set to 'false' to always build a new environment
